### ISSUE TITLE
目标元素或其父级元素添加非static定位的时候getTop失效

### ISSUE THREAD

**Issue by justbefree** [flykeying/autoTypewriting#1]

**Comment by justbefree** [comment]
`function getOffset (e) {
	var left = e.offsetLeft;
	var top = e.offsetTop;
	while (e.offsetParent) {
		e = e.offsetParent;
		left += e.offsetLeft;
		top += e.offsetTop;
	}
	return {
		left: left,
		top: top
	}
}`

**Comment by flykeying** [comment]
thanks i change
